version: '3'

services:
  master:
    image: locustio/locust:2.15.1
    user: root
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    environment:
      - LOCUSTFILE=${LOCUSTFILE}
      - TARGET_ADDRESS=${TARGET_ADDRESS}
      - USERS=${USERS}
      - TEST_NAME=${TEST_NAME}
      - VERSION=${VERSION}
    command:  -f "${LOCUSTFILE}" --master -H http://master:8089 --host "http://${TARGET_ADDRESS}" --users "${USERS}" --spawn-rate 50 --run-time 1m --csv /mnt/locust/result/${TEST_NAME}_${VERSION}/${USERS}  --autostart --autoquit 3 --reset-stats --csv-full-history

  worker:
    image: locustio/locust:2.15.1
    user: root
    volumes:
      - ./:/mnt/locust
    environment:
      - LOCUSTFILE=${LOCUSTFILE}
      - TARGET_ADDRESS=${TARGET_ADDRESS}
      - USERS=${USERS}
      - TEST_NAME=${TEST_NAME}
      - VERSION=${VERSION}
    command: -f "${LOCUSTFILE}" --worker --master-host master